# Copr Builder blueprint
#
# This blueprint was based on an ansible playbook for provisioning Copr builders
# https://pagure.io/fedora-infra/ansible/blob/main/f/roles/copr/backend/files/provision/provision_builder_tasks.yml
#
# Blueprint reference:
# https://osbuild.org/docs/user-guide/blueprint-reference/

name = "copr-builder"
description = "Prepare Copr builder image"
version = "0.0.1"
distro = "fedora-41"


# Install subscription-manager
# Install copr-builder and other latest packages
# Don't worry that this is on the top, and we enable additional repositories
# later. The blueprint is not evaluated from the top but in an order that
# Image Builder thinks is best. And we cannot move it lower because this syntax
# needs to be at the very top of the file
# https://osbuild.org/docs/user-guide/blueprint-reference/#footnote-label
packages = [
    { name = "subscription-manager" },
    { name = "copr-builder" },
    { name = "python3-copr-common" },

    # A new version of rpmlint fixes the following issue
    # https://pagure.io/FedoraReview/issue/461
    { name = "rpmlint" },

    # Tito 0.6.23 supports transitive submodule resolution
    # Requested on IRC by @abn
    { name = "tito" },

    # We want fedora-review 0.10.0 which generates `review.json` file
    # This is important for the fedora-review-service
    # https://github.com/FrostyX/fedora-review-service/issues/30
    { name = "fedora-review" },

    # Per report from @smooge, https://github.com/fedora-copr/copr/issues/2953
    { name = "bc" },

    # https://github.com/fedora-copr/copr/issues/3517
    { name = "pyp2spec" },
]


# TODO disable zram SWAP on builders, it is too small, issue 2077
# Not possible to do, I guess this is a related issue:
# https://github.com/osbuild/fedora-blueprints/issues/6

# put infra repos into yum.repos.d
[[customizations.repositories]]
id = "infrastructure-tags"
name = "Fedora Infrastructure tag $releasever - $basearch"
baseurls = ["https://kojipkgs.fedoraproject.org/repos-dist/f$releasever-infra/latest/$basearch/"]
enabled = true
gpgcheck = true
gpgkeys = ["https://infrastructure.fedoraproject.org/repo/infra/RPM-GPG-KEY-INFRA-TAGS"]

# TODO work-around for wrongly generated ami
# I guess we can remove this?

# TODO disable updates-testing
# TODO update the system
# TODO disable updates-testing, could be restored after update
# Can we assume the image is always fully updated and skip all of these?

# TODO clean dnf cache before checking for updated packages
# Can we skip this?

# TODO set lower metadata expire time to enforce download
# Can we temporarily move this to runtime?

# TODO fallback to the legacy crypto policies
# https://fedoraproject.org/wiki/Changes/StrongCryptoSettings
# Can we temporarily move this to runtime?

# TODO Collect facts about builder hardware
# We can probably skip this, it looks like starting_builder task

# TODO run /bin/copr-update-builder from copr-builder package
# Can we move this to runtime?

# mockbuilder user
[[customizations.user]]
name = "mockbuilder"
password = "mockbuilder"  # TODO Only for testing, remove afterward
groups = ["mock"]
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeTO0ddXuhDZYM9HyM0a47aeV2yIVWhTpddrQ7/RAIs99XyrsicQLABzmdMBfiZnP0FnHBF/e+2xEkT8hHJpX6bX81jjvs2bb8KP18Nh8vaXI3QospWrRygpu1tjzqZT0Llh4ZVFscum8TrMw4VWXclzdDw6x7csCBjSttqq8F3iTJtQ9XM9/5tCAAOzGBKJrsGKV1CNIrfUo5CSzY+IUVIr8XJ93IB2ZQVASK34T/49egmrWlNB32fqAbDMC+XNmobgn6gO33Yq5Ly7Dk4kqTUx2TEaqDkZfhsVu0YcwV81bmqsltRvpj6bIXrEoMeav7nbuqKcPLTxWEY/2icePF"

# setup 10x more fds in limits.conf
[[customizations.files]]
path = "/etc/security/limits.d/50-copr-fds.conf"
mode = "0644"
user = "root"
group = "root"
data = """
* soft nofile 10240
* hard nofile 10240
"""

# TODO disable core dumps
# Can we temporarily move this to runtime?

# TODO Remove %_install_langs from /etc/rpm/macros.image-language-conf
# Can we temporarily move this to runtime?

# Disable DNF makecache timer
# Disable DNF makecache service
# Disable hcn-init service on ppc64le which implies NetworkManager-wait-online
# Stop and disable systemd-oomd, rhbz 2051154
[customizations.services]
disabled = [
    "systemd-oomd",
    "dnf-makecache.timer",
    "dnf-makecache.service",
    "hcn-init.service",
]

# TODO detect package versions
# Can we remove this?

# TODO assure up2date packages
# Can we move this to runtime?

# TODO Set up motd for builder
# Can we move this to runtime?
